# Generated by Django 5.2.4 on 2025-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="langue",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English")],
                default="fr",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[("light", "Clair"), ("dark", "Sombre")],
                default="light",
                max_length=10,
            ),
        ),
    ]
