[phases.setup]
nixPkgs = ["python312", "libGL", "libGLU"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "python manage.py migrate",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn urbin.wsgi:application --bind 0.0.0.0:$PORT"
